---
name: "Vprofile IAC"

on:
  push:
    branches:
      - stage
      - main
    paths:
      - terraform/**
  pull_request:
    branches:
      - main
    paths:
      - terraform/**

env:
  # Credentials for deploying to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # S3 Bucket for storing Terraform state files
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  AWS_REGION: "eu-central-1"
  EKS_CLUSTER: "vprofile-eks"

jobs:
  terraform:
    name: "Apply Terraform code changes"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v6
      
      - name: "Setup Terraform with specified version on the runner"
        uses: hashicorp/setup-terraform@v3
        #with:
        #  terraform_version: 1.14.0
      
      - name: "Terraform Init"
        id: tf_init
        run: terraform init -backend-config="bucket=${{ env.BUCKET_TF_STATE }}"

      - name: "Terraform format check"
        id: tf_fmt
        run: terraform fmt -check

      - name: "Terraform Validate"
        id: tf_validate
        run: terraform validate

      - name: "Terraform Plan"
        id: tf_plan
        run: terraform plan -no-color -input=false -out tfplan
        continue-on-error: true

      - name: "Terraform plan status"
        if: steps.tf_plan.outcome == 'failure'
        run: exit 1
